server:
  port: 8888 #项目启动访问端口
spring:
  application:
    name: goods
  datasource: #连接数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/heima-estate?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root #数据库用户
    password: root #数据库密码，需要根据实际情况进行填写
  servlet:
    multipart: #文件上传配置
      max-file-size: 10MB
      max-request-size: 50MB
